### ISSUE TITLE
tessaract trainer not working

### ISSUE THREAD

**Issue by astamiviswakarma** [zendalona/lios#10]
Hi, we are using archlinux and facing issue running train-tesseract. 
```
/usr/lib/python3.7/site-packages/lios/ui/gtk/loop.py:21: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/lib/python3.7/site-packages/lios/ui/gtk/terminal.py:21: PyGIWarning: Vte was imported without specifying a version first. Use gi.require_version('Vte', '2.91') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GObject, Vte

(train-tesseract:30997): Gtk-WARNING **: 14:22:07.286: Cannot connect attribute 'text' for cell renderer class 'lios+ui+gtk+tree_view+CellRendererToggle' since attribute does not exist
language_combobox_changed Started
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/site-packages/lios/train_tesseract.py", line 643, in language_combobox_changed
    self.output_terminal.run_command(cmd)
  File "/usr/lib/python3.7/site-packages/lios/ui/gtk/terminal.py", line 48, in run_command
    self.feed_child(command, length)
TypeError: Vte.Terminal.feed_child() takes exactly 2 arguments (3 given)
```

**Comment by kaffeeringe** [comment]
Same. Ubuntu 21.10

**Comment by Nalin-x-Linux** [comment]
Tesseract Trainer GUI discontinued.
