### ISSUE TITLE
Issue after fresh install

### ISSUE THREAD

**Issue by JVKeller** [zendalona/lios#25]
Receiving this error on a fresh git clone. Ubuntu 22.10
```
$ lios
/usr/local/lib/python3.10/dist-packages/lios/ui/gtk/print_dialog.py:26: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import PangoCairo

(lios:8645): Gtk-WARNING **: 12:04:54.677: Cannot connect attribute 'text' for cell renderer class 'lios+ui+gtk+tree_view+CellRendererToggle' since attribute does not exist
Traceback (most recent call last):
  File "/usr/bin/lios", line 35, in <module>
    linux_intelligent_ocr_solution(args.files)
  File "/usr/local/lib/python3.10/dist-packages/lios/main.py", line 347, in __init__
    self.make_preferences_effective()
  File "/usr/local/lib/python3.10/dist-packages/lios/main.py", line 1328, in make_preferences_effective
    lang = languages[self.preferences.language]
IndexError: list index out of range

```

**Comment by JVKeller** [comment]
Sorry, Didn't realize there was another post about this. Still broken I guess.
